# Generated by Django 5.2.15 on 2026-07-30 12:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
