# Generated by Django 5.2.15 on 2026-07-30 12:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_proofs/'),
        ),
    ]
