# Generated by Django 5.2.15 on 2026-07-31 06:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_team_lead_approved_task_team_lead_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team_lead_approved',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_lead_approved_by',
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_proofs/'),
        ),
    ]
