# Generated by Django 5.2.15 on 2026-08-01 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_team_lead_approved_task_team_lead_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team_lead_approved',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_lead_approved_by',
        ),
        migrations.AddField(
            model_name='task',
            name='team_lead_approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='team_lead_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='team_lead_decided_by',
            field=models.ForeignKey(blank=True, help_text='Team Lead who approved or rejected this cross-team assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('PRIORITY_CHANGED', 'Priority changed'), ('PROGRESS_UPDATED', 'Progress updated'), ('DUE_DATE_CHANGED', 'Due date changed'), ('REASSIGNED', 'Reassigned'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment added'), ('ATTACHMENT_REMOVED', 'Attachment removed'), ('APPROVAL_REQUESTED', 'Team lead approval requested'), ('APPROVAL_GRANTED', 'Team lead approval granted'), ('APPROVAL_REJECTED', 'Team lead approval rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('PRIORITY_CHANGED', 'Priority changed'), ('PROGRESS_UPDATED', 'Progress updated'), ('DUE_DATE_CHANGED', 'Due date changed'), ('REASSIGNED', 'Reassigned'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment added'), ('ATTACHMENT_REMOVED', 'Attachment removed'), ('APPROVAL_REQUESTED', 'Team lead approval requested'), ('APPROVAL_GRANTED', 'Team lead approval granted'), ('APPROVAL_REJECTED', 'Team lead approval rejected')], max_length=20),
        ),
    ]
