# Generated by Django 5.2.15 on 2026-08-01 06:58

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_team_lead_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PRIORITY_CHANGED', 'Priority changed'), ('PROGRESS_UPDATED', 'Progress updated'), ('DUE_DATE_CHANGED', 'Due date changed'), ('REASSIGNED', 'Reassigned'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment added'), ('ATTACHMENT_REMOVED', 'Attachment removed'), ('APPROVAL_REQUESTED', 'Team lead approval requested'), ('APPROVAL_GRANTED', 'Team lead approval granted'), ('APPROVAL_REJECTED', 'Team lead approval rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PRIORITY_CHANGED', 'Priority changed'), ('PROGRESS_UPDATED', 'Progress updated'), ('DUE_DATE_CHANGED', 'Due date changed'), ('REASSIGNED', 'Reassigned'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment added'), ('ATTACHMENT_REMOVED', 'Attachment removed'), ('APPROVAL_REQUESTED', 'Team lead approval requested'), ('APPROVAL_GRANTED', 'Team lead approval granted'), ('APPROVAL_REJECTED', 'Team lead approval rejected')], max_length=20),
        ),
    ]
