# Generated by Django 5.2.15 on 2026-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_description_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pre_cancel_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
