# Generated by Django 5.2.15 on 2026-08-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_pre_cancel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PRIORITY_CHANGED', 'Priority changed'), ('PROGRESS_UPDATED', 'Progress updated'), ('DUE_DATE_CHANGED', 'Due date changed'), ('REASSIGNED', 'Reassigned'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment added'), ('ATTACHMENT_REMOVED', 'Attachment removed'), ('APPROVAL_REQUESTED', 'Team lead approval requested'), ('APPROVAL_GRANTED', 'Team lead approval granted'), ('APPROVAL_REJECTED', 'Team lead approval rejected'), ('APPROVAL_PRE_GRANTED', 'Team lead approval granted at assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PRIORITY_CHANGED', 'Priority changed'), ('PROGRESS_UPDATED', 'Progress updated'), ('DUE_DATE_CHANGED', 'Due date changed'), ('REASSIGNED', 'Reassigned'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment added'), ('ATTACHMENT_REMOVED', 'Attachment removed'), ('APPROVAL_REQUESTED', 'Team lead approval requested'), ('APPROVAL_GRANTED', 'Team lead approval granted'), ('APPROVAL_REJECTED', 'Team lead approval rejected'), ('APPROVAL_PRE_GRANTED', 'Team lead approval granted at assignment')], max_length=20),
        ),
    ]
