# Generated by Django 5.2.15 on 2026-09-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_taskactivity_verb_alter_tasknotification_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'Development'), ('TESTING', 'Testing'), ('MARKETING', 'Marketing'), ('HR', 'HR'), ('TRAINER', 'Trainer'), ('BDE', 'Business Development'), ('UI_UX', 'UI/UX'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='designation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'QA Analyst '), ('MARKETING_LEAD', 'Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('TRAINER', 'Technical Trainer'), ('BDE', 'Business Development Executive'), ('UI_UX_LEAD', 'UI/UX Lead'), ('UI/UX_DESIGNER', 'UI/UX Designer'), ('INTERN', 'Intern'), ('FOUNDER_TECHNICAL_MENTOR', 'Founder & Technical Mentor')], default='', max_length=30),
        ),
    ]
