# Generated by Django 5.2 on 2026-07-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'Testing'), ('DIGITAL_MARKETING_LEAD', 'Digital Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('INTERN', 'Intern')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('REPORTING_PERSON', 'Reporting person'), ('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], default='EMPLOYEE', max_length=30),
        ),
    ]
