# Generated by Django 5.2 on 2026-07-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_designation_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'Testing'), ('DIGITAL_MARKETING_LEAD', 'Digital Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('INTERN', 'Intern')], max_length=30, null=True),
        ),
    ]
