# Generated by Django 5.2.15 on 2026-07-18 12:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_is_superuser_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='employee_photos/'),
        ),
    ]
