# Generated by Django 5.2.15 on 2026-07-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REPORTING_PERSON', 'Reporting person'), ('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], default='REPORTING_PERSON', max_length=30),
        ),
    ]
