# Generated by Django 5.2.15 on 2026-07-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(choices=[('DEVELOPER', 'Development'), ('TESTING', 'Testing'), ('MARKETING', 'Marketing'), ('HR', 'HR'), ('TRAINER', 'Trainer'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'Testing'), ('DIGITAL_MARKETING_LEAD', 'Digital Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('TRAINER', 'Trainer'), ('INTERN', 'Intern')], max_length=30, null=True),
        ),
    ]
