# Generated by Django 5.2.15 on 2026-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_team_department_alter_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'Testing'), ('DIGITAL_MARKETING_LEAD', 'Digital Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('TRAINER', 'Trainer'), ('BDE', 'Business Development Executive'), ('UI/UX_DESIGNER', 'UI/UX Designer'), ('INTERN', 'Intern'), ('FOUNDER_TECHNICAL_MENTOR', 'Founder & Technical Mentor')], max_length=30, null=True),
        ),
    ]
