# Generated by Django 5.2.15 on 2026-09-08 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_person',
            field=models.ForeignKey(blank=True, help_text="The Reporting Person this employee reports to. Determines whose 'My Team' this employee appears in.", limit_choices_to={'role': 'REPORTING_PERSON'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(choices=[('DEVELOPER', 'Development'), ('TESTING', 'Testing'), ('MARKETING', 'Marketing'), ('HR', 'HR'), ('TRAINER', 'Trainer'), ('BDE', 'Business Development'), ('UI_UX', 'UI/UX'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'QA Analyst '), ('MARKETING_LEAD', 'Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('TRAINER', 'Technical Trainer'), ('BDE', 'Business Development Executive'), ('UI_UX_LEAD', 'UI/UX Lead'), ('UI/UX_DESIGNER', 'UI/UX Designer'), ('INTERN', 'Intern'), ('FOUNDER_TECHNICAL_MENTOR', 'Founder & Technical Mentor')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('MANAGER', 'Manager'), ('HR', 'HR'), ('TECHNICAL_LEAD', 'Technical Lead'), ('TEAM_LEAD_DEVELOPER', 'Team Lead (Developer)'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('TESTING_LEAD', 'Testing Lead'), ('TESTING', 'QA Analyst '), ('MARKETING_LEAD', 'Marketing Lead'), ('DIGITAL_MARKETING_EXECUTIVE', 'Digital Marketing Executive'), ('TRAINER', 'Technical Trainer'), ('BDE', 'Business Development Executive'), ('UI_UX_LEAD', 'UI/UX Lead'), ('UI/UX_DESIGNER', 'UI/UX Designer'), ('INTERN', 'Intern'), ('FOUNDER_TECHNICAL_MENTOR', 'Founder & Technical Mentor')], max_length=30)),
                ('department', models.CharField(blank=True, choices=[('DEVELOPER', 'Development'), ('TESTING', 'Testing'), ('MARKETING', 'Marketing'), ('HR', 'HR'), ('TRAINER', 'Trainer'), ('BDE', 'Business Development'), ('UI_UX', 'UI/UX'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='The main designation shown everywhere the app expects a single value.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='accounts.team')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
